name: Merge main into report
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Check out report"
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: report
      - name: Merge main into report
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: report
          github_token: ${{ github.token }}
